#!/bin/bash

USER_NAME=hyper

# source $HOME/shellscripts/server_management_ncp/main
# source ~/.bashrc

setup -d -n -g

# 도커 User Add
adduser $USER_NAME

usermod -aG docker $USER_NAME

chmod 666 /run/docker.sock

sed -i "s/\(^sudo.*$\)/&$USER_NAME/" /etc/group

service docker restart

function hyper_commands() {
	git clone https://github.com/0strich/shellscripts.git
	git clone https://github.com/0strich/hyperledger.git

	source $HOME/shellscripts/server_management_ncp/main

	echo "export PATH=$PATH:$(pwd)/hyperledger/scripts" >>~/.bashrc
	source ~/.bashrc
}

# $USER_NAME 계정 설정
su - $USER_NAME -c "
	$(declare -f hyper_commands)
	hyper_commands
"
