#!/bin/bash
set -e

MY_PATH=$(dirname $(readlink -f $0))

echo "export PATH=\$PATH:$MY_PATH/scripts" >>~/.bashrc
echo "export PATH=\$PATH:/usr/local/go/bin" >>~/.bashrc
# echo "IPFS_PATH=~/.ipfs" >>~/.bashrc
eval "source ~/.bashrc"

# Reload the current shell to apply changes to PATH
. ~/.bashrc
