name: Calier test
version: "2.0.0"

caliper:
  blockchain: fabric

channels:
  - channelName: mychannel
    contracts:
      - id: basic

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
        - name: "User1"
          clientPrivateKey:
            path: "/tmp/crypto/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/dfe0b4b2e7dfb1f835ef1af8f11aa513a2dba2d4ea30e6399979e798e6b23543_sk"
          clientSignedCert:
            path: "/tmp/crypto/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem"
    connectionProfile:
      path: "/tmp/crypto/peerOrganizations/org1.example.com/connection-org1.yaml"
      discover: true
