#!/bin/bash
set -e

echo 'export PATH=$PATH:$HOME/shellscripts/server_management/bin' >>~/.bashrc
echo 'export PATH=$PATH:$HOME/shellscripts/server_management/deploy' >>~/.bashrc
echo 'export PATH=$PATH:$HOME/shellscripts/blockchain/hyperledger/fabric/bin' >>~/.bashrc

source ~/.bashrc
