#!/bin/bash

set -e

function dump() {
	local PROJECT=$1
	local OUT_PATH=$2

	case $PROJECT in
	saltmine)
		MONGO_HOST=$SALTMINE_MONGO_HOST
		MONGO_PORT=$SALTMINE_MONGO_PORT
		MONGO_USERNAME=$SALTMINE_MONGO_USERNAME
		MONGO_PASSWORD=$SALTMINE_MONGO_PASSWORD
		;;
	modoomanager)
		MONGO_HOST=$MODOOMANAGER_MONGO_HOST
		MONGO_PORT=$MODOOMANAGER_MONGO_PORT
		MONGO_USERNAME=$MODOOMANAGER_MONGO_USERNAME
		MONGO_PASSWORD=$MODOOMANAGER_MONGO_PASSWORD
		;;
	ilharu)
		MONGO_HOST=$ILHARU_MONGO_HOST
		MONGO_PORT=$ILHARU_MONGO_PORT
		MONGO_USERNAME=$ILHARU_MONGO_USERNAME
		MONGO_PASSWORD=$ILHARU_MONGO_PASSWORD
		;;
	tria)
		MONGO_HOST=$TRIA_MONGO_HOST
		MONGO_PORT=$TRIA_MONGO_PORT
		MONGO_USERNAME=$TRIA_MONGO_USERNAME
		MONGO_PASSWORD=$TRIA_MONGO_PASSWORD
		;;
	austin)
		MONGO_HOST=$AUSTIN_MONGO_HOST
		MONGO_PORT=$AUSTIN_MONGO_PORT
		MONGO_USERNAME=$AUSTIN_MONGO_USERNAME
		MONGO_PASSWORD=$AUSTIN_MONGO_PASSWORD
		;;
	*)
		echo "Please provide a project name (saltmine, modoomanager, vendor, develop, ilharu, tria)."
		exit 1
		;;
	esac

	mongodump --host $MONGO_HOST --port $MONGO_PORT --username $MONGO_USERNAME --password $MONGO_PASSWORD --out $OUT_PATH
}

PROJECT=$1

if [[ -z "$PROJECT" ]]; then
	echo "Please provide a project name (saltmine, modoomanager, vendor, develop, ilhau, tria)."
	exit 1
fi

BASE_PATH="/Users/patric/Programming/backup"
TODAY=$(date "+%Y-%m-%d")
BACKUP_PATH="$BASE_PATH/$PROJECT/$TODAY"

# 만약 해당 날짜의 디렉토리가 없다면 생성
[ ! -d $BACKUP_PATH ] && mkdir -p $BACKUP_PATH

dump $PROJECT $BACKUP_PATH

exit
