#!/bin/bash

pushd $HOME/shellscripts/hyperledger/caliper

# 키 업데이트 경로
PRIVATE_KEY_PATH=/tmp/crypto/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore
NEW_FILE_NAME=$(ls $PRIVATE_KEY_PATH | grep '_sk')
NEW_FILE_PATH=$PRIVATE_KEY_PATH/$NEW_FILE_NAME
# 키 업데이트

if [[ $OSTYPE == "darwin"* ]]; then
	sed -i "" "s|$PRIVATE_KEY_PATH/[^/]*_sk|$NEW_FILE_PATH|g" ./networks/networkConfig.yaml
else
	sed -i "s|$PRIVATE_KEY_PATH/[^/]*_sk|$NEW_FILE_PATH|g" ./networks/networkConfig.yaml
fi

if [ ! -d "node_modules" ]; then
	# CLI 설치
	npm install --only=prod @hyperledger/caliper-cli@0.4.2
	# SDK 바인딩
	npx caliper bind --caliper-bind-sut fabric:2.2
fi

if [ -f "$HOME/shellscripts/hyperledger/workloads/readEmployee.js" ]; then
	cp $HOME/shellscripts/hyperledger/workloads/createEmployee.js $HOME/shellscripts/hyperledger/caliper/workload/createEmployee.js
	cp $HOME/shellscripts/hyperledger/workloads/readEmployee.js $HOME/shellscripts/hyperledger/caliper/workload/readEmployee.js
	cp $HOME/shellscripts/hyperledger/workloads/verifyEmployee.js $HOME/shellscripts/hyperledger/caliper/workload/verifyEmployee.js
fi

# 커맨드 실행
npx caliper launch manager --caliper-workspace ./ --caliper-networkconfig networks/networkConfig.yaml --caliper-benchconfig benchmarks/myAssetBenchmark.yaml --caliper-flow-only-test --caliper-fabric-gateway-enabled

exit
