#!/bin/bash

set -e

# PARSED_OPTIONS=$(getopt -o ab:c --long optionA,optionB:,optionC -- "$@")

# eval set -- "$PARSED_OPTIONS"

while true; do
  case "$1" in
  -a | --optionA)
    echo "Option A"
    shift
    ;;
  -b | --optionB)
    echo "Option B, argument '$2'"
    shift 2
    ;;
  # --)
  #   shift
  #   break
  #   ;;
  *)
    echo "Unknown option: $1"
    exit 1
    ;;
  esac
done
