#!/bin/bash

set -e

source /project/mongodb/.env

BACKUP_DIR="/var/backups/mongodb"
DATE=$(date +"%Y%m%d")

docker exec mongodb mongodump --username $MONGO_INITDB_ROOT_USERNAME --password $MONGO_INITDB_ROOT_PASSWORD --out $BACKUP_DIR/$DATE

exit
