#!/bin/bash

set -e

# Load the environment variables from .env file
source /project/mongodb/.env

# Define backup directories for the container and the host
CONTAINER_BACKUP_DIR="/var/backups/mongodb"
HOST_BACKUP_DIR="/var/backups/mongodb"
DATE=$(date +"%Y%m%d%H%M") # Include the hour and minute

# Execute the backup command inside the MongoDB container
docker exec mongodb mongodump --username $MONGO_INITDB_ROOT_USERNAME --password $MONGO_INITDB_ROOT_PASSWORD --out $CONTAINER_BACKUP_DIR/$DATE

# Copy the backup data from the container to the host
docker cp mongodb:$CONTAINER_BACKUP_DIR/$DATE $HOST_BACKUP_DIR/$DATE

exit
