#!/bin/bash

set -e

# Check if no options were provided
if [ $# -eq 0 ]; then
  cat ~/.ssh/config
  exit 0
fi

while true; do
  case "$1" in
  -v | --view)
    vi ~/.ssh/config
    shift
    ;;
  -a | --auth)
    vi ~/.ssh/authorized_keys
    shift
    ;;
  -b | --optionB)
    echo "Option B, argument '$2'"
    shift 2
    ;;
  *)
    echo "Unknown option: $1"
    exit 1
    ;;
  esac
done
